server:
  port: 8081

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        input:
          group: admin
          destination: team3vod
          contentType: application/json
        output:
          destination: team3vod
          contentType: application/json
